import type { Locale } from '../i18n/ui';

const english: Record<string, string> = {
  "Cálculo y análisis": "Calculus and analysis",
  "Álgebra abstracta": "Abstract algebra",
  "Análisis funcional": "Functional analysis",
  "Variable compleja": "Complex analysis",
  "Topología": "Topology",
  "Métodos numéricos": "Numerical methods",
  "Ecuaciones diferenciales": "Differential equations",
  "Modelización matemática": "Mathematical modelling",
  "Inferencia estadística": "Statistical inference",
  "Estadística multivariante": "Multivariate statistics",
  "Álgebra computacional": "Computational algebra",
  "Lógica y matemática discreta": "Logic and discrete mathematics",
  "Computabilidad y complejidad": "Computability and complexity",
  "Programación orientada a objetos": "Object-oriented programming",
  "Arquitectura de computadores": "Computer architecture",
  "Sistemas operativos": "Operating systems",
  "Redes de computadores": "Computer networks",
  "Concurrencia y sistemas distribuidos": "Concurrency and distributed systems",
  "Bases de datos": "Databases",
  "Ingeniería de servidores": "Server engineering",
  "Informática gráfica": "Computer graphics",
  "Interacción persona-ordenador": "Human-computer interaction",
  "Fundamentos físicos y electrónicos": "Physics and electronics foundations",
  "Búsqueda y planificación en IA": "AI search and planning",
  "Metaheurísticas": "Metaheuristics",
  "Clustering y reglas de asociación": "Clustering and association rules",
  "Preprocesamiento de datos": "Data preprocessing",
  "Aprendizaje avanzado": "Advanced machine learning",
  "Minería de texto y PLN": "Text mining and NLP",
  "Análisis de redes sociales": "Social network analysis",
  "Big Data y procesamiento distribuido": "Big Data and distributed processing",
  "Bioinformática y datos ómicos": "Bioinformatics and omics",
  "Inteligencia de negocio": "Business intelligence",
  "Transferencia de conocimiento": "Knowledge transfer",
  "Apache Spark": "Apache Spark",
  "Hadoop y MapReduce": "Hadoop and MapReduce",
  "MongoDB y NoSQL": "MongoDB and NoSQL",

  'Estadística': 'Statistics',
  'Probabilidad': 'Probability',
  'Álgebra lineal': 'Linear algebra',
  'Optimización': 'Optimization',
  'Geometría diferencial': 'Differential geometry',
  'Algoritmos y estructuras': 'Algorithms and data structures',
  'Arquitectura de software': 'Software architecture',
  'Integración continua': 'Continuous integration',
  'Linux y shell': 'Linux and shell',
  'Series temporales': 'Time series',
  'Detección de anomalías': 'Anomaly detection',
  'Inferencia causal': 'Causal inference',
  'Evaluación de modelos': 'Model evaluation',
  'Riesgo de crédito': 'Credit risk',
  'Visión por computador': 'Computer vision',
  'Redes de grafos': 'Graph neural networks',
  'LiDAR y datos públicos': 'LiDAR and public data',
  'Azure y Microsoft 365': 'Azure and Microsoft 365',
  'Español': 'Spanish',
  'Inglés': 'English',
  'Francés': 'French',
};

export function skillLabel(label: string, locale: Locale): string {
  return locale === 'en' ? (english[label] ?? label) : label;
}
