title: German Padua
email: german.padua@outlook.es
description: >-
  Portafolio de German Padua - Ingeniero Informático y Matemático, apasionado por la Inteligencia Artificial y la Ciencia de Datos.
baseurl: ""
url: "https://germanpadua.github.io"
twitter_username: 
github_username:  germanpadua
linkedin_username: german-jose-padua-pleguezuelo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be defined by specific file, by specific dir, or by glob.
# Sample: all files that have dot as first character
# - .sass-cache/
# - .jekyll-cache/
# - gemfiles/
# - Gemfile
# - Gemfile.lock
# - node_modules/
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
